### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by mehcode** [chemoish/atom-pane-layout#10]
![screenshot from 2015-04-22 12 19 08](https://cloud.githubusercontent.com/assets/753919/7283186/c9d12248-e8e9-11e4-81f7-ce0883fd30d1.png)

**Comment by erikanderson** [comment]
yeah, I got this too. Here is clear text: 
```
pane-layout-plus (2 deprecations)
Use ::paneForURI instead.
Called 7 timesCreate Issue on pane-layout-plus repo
Workspace.paneForUri - /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:1003:7
Object.activateItem - /Users/erik/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:13:26
Object.formatLayout - /Users/erik/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:101:5
Object.layout - /Users/erik/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:13:24
Use ::activateItemForURI instead.
Called 7 timesCreate Issue on pane-layout-plus repo
Pane.activateItemForUri - /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:831:12
Object.activateItem - /Users/erik/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:17:9
Object.formatLayout - /Users/erik/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:101:5
Object.layout - /Users/erik/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:13:24
```

**Comment by chemoish** [comment]
Thanks for reporting. I'll try to look into it in the next couple of days.

Feel free to submit PR if you feel so inclined.

**Comment by chemoish** [comment]
Deprecation cop is annoying. I cannot get it to show the error messages on Windows, but I fixed the URI calls anyways.

Fixed by 743190b8461809c362e4ae823de711fbb9e4e8ab

**Comment by mehcode** [comment]
Thanks; not too important at the moment but I'd hate to lose an awesome package whenever atom goes 1.0.

**Comment by erikanderson** [comment]
thanks, this fixed the original deprecation warnings but I am still getting these: 

![screen shot 2015-04-27 at 5 32 04 pm](https://cloud.githubusercontent.com/assets/4634290/7360043/6f6ca37c-ed03-11e4-9bc2-b5a611498d19.png)

**Comment by chemoish** [comment]
Please see https://github.com/atom/atom/issues/6310

Not sure if this is related to this package or if its related to another package (I think it is). They are working on updating deprecation cop to display the related package instead.

**Comment by erikanderson** [comment]
Yeah, could be. However this is the only package I have installed at the moment and when I disable it the deprecation warnings go away. I am on OSX 10.10.3 btw

**Comment by erikanderson** [comment]
Latest update 0.196.0: 

pane-layout-plus (2 deprecations)
The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
Called 1 time
Package.activateResources - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:303:19
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:199:21
Package.measure - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15
Package.activate - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14
Use activationCommands instead of activationEvents in your package.json Commands should be grouped by selector as follows:

  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
Called 1 time
Package.getActivationCommands - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:790:9
Package.hasActivationCommands - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:20
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:24
Package.measure - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15

**Comment by chemoish** [comment]
Fixed by https://github.com/chemoish/atom-pane-layout/commit/424ccead8eaa33657a604019e494be365fd2cf36

**Comment by erikanderson** [comment]
Thanks, no more warnings. You the man
